# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46176474d5ed60db7ae0e36b253daa51466420dfbbb3f0284562ccf6e24a88f2b7a4c30c1bfffff8033cda2ab4276eeef343a66f472514c2f3ea236dbcce4676

test:
  secret_key_base: 791b997d0351cf63e11dafffdbba4c28745570c9feb40890921121f59b646bb6f3b162e4d1f795a2e0693db0491d3abe245f2beb9b6b6d7422b26267ea4b7d4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
